### ISSUE TITLE
How to configure/use

### ISSUE THREAD

**Issue by soreau** [nwg-piotr/nwgcc#1]
Hi, I used `python3 ./setup.py install --prefix=$prefix` and then ran `$prefix/lib/python3.8/site-packages/nwgcc-0.0.1-py3.8.egg/nwgcc/main.py` and it runs, but nothing appears on screen. The config and other files are at `~/.config/nwgcc/` and it doesn't output any error message.

**Comment by soreau** [comment]
I have tried in X+compiz and wayfire.

**Comment by nwg-piotr** [comment]
My `nwgcc` command still looks like this:

```
$ cat ~/bin/nwgcc
#!/bin/sh

python /home/piotr/PycharmProjects/nwgcc/nwgcc/main.py $@
```

Could you try `nwgcc -d`?

**Comment by soreau** [comment]
X:
```
$ /tmp/nwgcc -d
Checking commands availability:
  'upower' found
  'acpi' not found!
  'bluetoothctl' found
  'light' not found!
  'uname' found
  'iwgetid' found
  'echo' found
  'systemctl' found
Icons: Custom light
Style: '/home/scott/.config/nwgcc/style.css'
```
Wayfire:
```
$ /tmp/nwgcc -d
Checking commands availability:
  'upower' found
  'acpi' not found!
  'bluetoothctl' found
  'light' not found!
  'uname' found
  'iwgetid' found
  'echo' found
  'systemctl' found
Icons: Custom light
Style: '/home/scott/.config/nwgcc/style.css'
```

**Comment by nwg-piotr** [comment]
Are `python-gobject` and `python-pyalsa` packages installed?

**Comment by soreau** [comment]
I did have to install python3-pyalsa because it wouldn't run without it but python3-gi is already installed and python-gobject is a package for python2 here.

**Comment by nwg-piotr** [comment]
Yep, I need to add a check for this package. But did it help?

**Comment by soreau** [comment]
You are suggesting to install the python2 gobject package?

**Comment by nwg-piotr** [comment]
No idea. On Arch there's a python3 package: `python-gobject` with `gobject-introspection-runtime` as a dependency.

**Comment by soreau** [comment]
I see. Here, I am guessing it's: `python3-gi - Python 3 bindings for gobject-introspection libraries`.

Just to be clear, I am reading the source correctly to expect a window to show when main.py is run?

**Comment by nwg-piotr** [comment]
This should give you no error in proper environment:

```
$ python3
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Gtk', '3.0')
>>> from gi.repository import Gtk
>>>
```

**Comment by nwg-piotr** [comment]
Yes, running `main.py` is all you need.

**Comment by soreau** [comment]
And I am not seeing [this message](https://github.com/nwg-piotr/nwgcc/blob/master/nwgcc/main.py#L520), is it a problem?

**Comment by nwg-piotr** [comment]
It should appear always, except for `nwgcc -h`.

**Comment by soreau** [comment]
Hm, I suppose it's getting stuck between the Style path message and that one, then?

**Comment by soreau** [comment]
```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Gtk', '3.0')
>>> from gi.repository import Gtk
>>> 
```

**Comment by nwg-piotr** [comment]
The next line instantiates the MyWindow(Gtk.Window) class.

**Comment by soreau** [comment]
aha, found it. It is the bluetooth stuff hanging up

**Comment by soreau** [comment]
when I comment out [this portion](https://github.com/nwg-piotr/nwgcc/blob/master/nwgcc/main.py#L382-L384), it shows the window.

**Comment by nwg-piotr** [comment]
Ha! BT detection is troublesome and definitely needs some more work. You can turn off the BT line in preferences.

**Comment by soreau** [comment]
Wow, I have to say, this is really nice, I only wish it were in C or C++ so it could more easily talk to wayfire via protocol, but I guess this is yet one more place dbus shines. I was hoping to have a menu to fulfill [this window menu portion of xdg spec](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L669-687) but never really got started. It would be for right-click-on-titlebar and right-click-on-window-list-item menu, and maybe right-click-on-desktop. But back to your original issue of placement..

I think if the menu were called as a result of this function, wayfire could place the window at the mouse position without the need for gtk_window_set_position or the like.

**Comment by nwg-piotr** [comment]
My C++ is very basic. [My only C++ project](https://github.com/nwg-piotr/nwg-launchers) is quite decent thanks to better skilled contributors. I've been trying hard to fall in love with it, but I keep failing. :rofl: 

For educational purposes (and performance), I'm going to write nwgcc again in Go. One day.

**Comment by nwg-piotr** [comment]
BTW: enabling `bluetooth.service` should prevent the code from hanging. I used to know it at the beginning, but I forgot.

**Comment by soreau** [comment]
bluetooth.service is enabled here. IMHO, nwgcc shouldn't hang regardless of what state the system is in.

**Comment by nwg-piotr** [comment]
This needs more attention. Thanks for discovering the issue.

**Comment by soreau** [comment]
Aside from this small problem, it is very nice and functional OOTB. Thanks for your work!

**Comment by nwg-piotr** [comment]
It's 4 am here, but tomorrow I'm working remotely. It may mean some time to work on the code. ;)

**Comment by AdrianVovk** [comment]
Unrelated, but is there any way for cSH to hook into show_window_menu?

**Comment by soreau** [comment]
@AdrianVovk As the spec states, "This request asks the compositor to pop up such a window menu at the given position, relative to the local surface coordinates of the parent surface.", meaning that the compositor should handle this request and spawn a program which will create a surface to be placed. So basically, this is simply missing implementation in wayfire.

**Comment by soreau** [comment]
It might need a wlroots patch too, not sure.

**Comment by soreau** [comment]
Hi, I am writing to re-introduce the window-menu plugin. To update:
```
$ cd ./wf-install/wayfire-plugins-extra
$ git checkout window-menu
$ git fetch origin
$ git reset --hard origin/window-menu
```

The defaults expect [a script](https://github.com/nwg-piotr/nwgcc/issues/1#issuecomment-735497393) to be installed to `$PATH` called `nwgcc`. The plugin listens for clients to send the show_window_menu request and spawns the nwgcc command `nwgcc --name=nwgcc`. This changes the application identifier to nwgcc. Then there is the application identifier match option which is also set to nwgcc. This is how the plugin matches the surface and positions it, removes decorations (in the case of set_decorated(false)) and sets up a button handler so it knows when to tell the surface to close.

This means that right-clicking on gtk titlebars with CSD decoration should open nwgcc and position it.

**Comment by nwg-piotr** [comment]
It works perfectly well for me.
